wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1630231521
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.8.5
      5: 0.12.1
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.05
